// STUB — @frontend.eng scope ends here. This module fakes the SAD §4 async
// submit/poll contract (POST /api/runs, GET /api/runs/{run_id}) entirely on
// the client so the chat UI has something to drive without a real backend
// connection, which is @integration.eng's job. Replace `submitRun`/`pollRun`
// with real `fetch` calls against the FastAPI backend — the shapes below
// (JobRequisition, RunResultResponse, etc.) already match backend/app/models.py.

import type { JobRequisition, RunResultResponse, RunSubmissionResponse } from "./types";

const MOCK_REPORT = (requisition: JobRequisition) => `## Recommendations

**Top candidate for "${requisition.title}"**: Jordan Ellis — Senior Software Engineer, 7 years'
experience matching your stated requirements. Score: 92/100. Strong overlap with
"${requisition.requirements.slice(0, 60) || "the listed requirements"}".

1. **Jordan Ellis** — Score 92. Strong technical fit, referenceable open-source history.
2. **Priya Nair** — Score 87. Slightly light on the preferred qualifications, strong culture fit.
3. **Sam Okafor** — Score 81. Meets requirements, less relevant domain background.

## Outreach Guidance

- **Jordan Ellis**: reach out via email; lead with the specific project mentioned in their portfolio.
- **Priya Nair**: LinkedIn InMail; mention the perks (${requisition.perks || "n/a"}) up front.
- **Sam Okafor**: warm intro preferred if available before a cold email.

*This is placeholder content generated by the frontend stub (\`runClient.ts\`) — no LLM or search
provider was called. @integration.eng should swap this for the real \`POST /api/runs\` /
\`GET /api/runs/{run_id}\` round trip.*`;

let counter = 0;

export function submitRun(requisition: JobRequisition): Promise<RunSubmissionResponse> {
  void requisition; // unused by the stub; the real endpoint (SAD §4) takes it as the request body
  counter += 1;
  const run_id = `stub-run-${counter}`;
  return new Promise((resolve) => {
    setTimeout(() => resolve({ run_id, status: "pending" }), 300);
  });
}

export function pollRun(
  run_id: string,
  requisition: JobRequisition,
  elapsedMs: number
): Promise<RunResultResponse> {
  const now = new Date(elapsedMs).toISOString();
  return new Promise((resolve) => {
    setTimeout(() => {
      if (elapsedMs < 2600) {
        resolve({
          run_id,
          status: "running",
          created_at: now,
          updated_at: now,
          report: null,
          error: null,
        });
        return;
      }
      resolve({
        run_id,
        status: "succeeded",
        created_at: now,
        updated_at: now,
        report: MOCK_REPORT(requisition),
        error: null,
      });
    }, 500);
  });
}
